# Site settings
title: Cintoia
email: info@cintoia.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.cintoia.com" # the base hostname & protocol for your site
phone: "+358447447002"
twitter_username: cintoia
instagram_username: cintoiafeel
loginurl: "/logins"

# Build settings
markdown: kramdown
